<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * News list page
 *
 * @see Fox_News_View_News
 */
?>
<?php
$newsCollection = $this->getNews();
?>
<ul id="ourNews">
    <?php foreach ($newsCollection as $news): ?>
        <li>
            <div class="mi-cover">
                <div class="mi-content">
                    <div class="list_news_title"><h3><?php echo $news['title'] ?></h3></div>
                    <div class="list_news_content"><?php echo $news['content']; ?></div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>        
</ul>