<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */
/**
 * News sidebar
 *
 * @see Fox_News_View_News
 */
?>
<?php $newsCollection = $this->getNews(); ?>
<div class="right_cont news_wrap">
<h2 class="sub-heading"><?php echo $this->_('News');?> &amp; <?php echo $this->_('Events');?></h2>
<div class="news_cont">
    <ul id="news_rotator">
        <?php foreach ($newsCollection as $news): ?>
            <li>
                <p><?php echo (strlen($news['title'])>100)?(substr($news['title'], 0, 100).'...'):$news['title']; ?></p>
                
            </li>
        <?php endforeach; ?>
    </ul>
    <p class="read_more"><a title="News Updates" href="<?php echo $this->getListUrl(); ?>"><?php echo $this->_('read more...');?></a></p>
</div>
</div>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#news_rotator').jscroll({
            duration:3000
        });
    });
</script>