<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Head content
 *
 * @see Fox_Core_View_Html_Head
 */
?>
<?php $helper=Fox::getHelper('core/head'); ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="<?php echo $this->getMetaDescription();?>" />
<meta name="keywords" content="<?php echo $this->getMetaKeywords();?>" />
<meta name="robots" content="<?php echo $this->getRobots();?>" />
<link href="<?php echo $this->getFavicon(); ?>" rel="shortcut icon" />
<title><?php echo $this->getTitle();?></title>
<?php echo $this->getScripts();?>
<?php
echo $helper->getHTML();
?>