<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Contact detail view page
 *
 * @see Fox_Contact_View_Admin_Contact_View_Form
 */
?>
<?php
$contactData = $this->getContactDetail();
?>
<table width="40%" border="0" align="center" cellpadding="0" cellspacing="0" class="admin_contact">
    <tr>
        <td>
            <ul>
                <li>
                    <span class="text"><strong>Name</strong></span>
                    <span>:</span>
                    <span class="detail"><?php echo $contactData->getName(); ?></span>
                </li>
                <li>
                    <span class="text"><strong>Email</strong></span>
                    <span>:</span>
                    <span class="detail"><?php echo $contactData->getEmail() ?></span>
                </li>
                <li>
                    <span class="text"><strong>Subject</strong></span>
                    <span>:</span>
                    <span class="detail"><?php echo $contactData->getSubject() ?></span>
                </li>
                <li>
                    <span class="text"><strong>Message</strong></span>
                    <span>:</span>
                    <span class="detail"><?php echo $contactData->getMessage() ?></span>
                </li>

            </ul>
        </td>
    </tr>
</table>