<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */
/**
 * Recent contact requests dashboard block
 *
 * @see Fox_Contact_View_Admin_Dashboard
 */
$recentContacts=$this->getRecentContacts(10);
?>
<h2>Recent Contact Requests</h2>
<div class="dash_left_cont">
    <?php if ($recentContacts->getTotalItemCount() > 0) : ?>
        <ul>
            <?php foreach ($recentContacts as $contact): ?>
                <li>
                    <span class="recent_member_text">
                        <a href="<?php echo Fox::getUrl('contact/admin_contact/view', array('id' => $contact['id'])); ?>"><?php echo $contact['name']; ?></a>
                    </span>
                    <span class="recent_member_date"><?php echo Fox_Core_Model_Date::__toLocaleDate(strtotime($contact['contact_date']),'d M, Y') ?></span>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <ul><li class="dashboard_contact_no_records">No Records Found</li></ul>
    <?php endif; ?>
</div>