<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 *

/**
 * Admin head content
 *
 * @see Fox_Admin_View_Html_Head
 */
?>
<?php $helper = Fox::getHelper('core/head'); ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->getTitle(); ?></title>
<?php
echo Fox::getHelper('core/head')->getHTML();
?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        activateMenu();        
        activateAjaxLoader();
    });    
    function activateMenu(){
        jQuery('.admin-nav-menu').css('display','none');
        jQuery('ul.admin-nav-menu a').each(function(i,o){            
            var $ob=jQuery(o);                        
            if(window.location.href.indexOf($ob.attr('href'))>=0){
                $ob.parents('ul.admin-nav-menu>li').addClass('active').children('a').addClass('main');
                return false;
            }
        }); 
        jQuery('.admin-nav-menu').css('display','block');
    }
    function activateAjaxLoader(){
        $loader=jQuery('.ajax-loader');
        $loader.css('top',($loader.parent().innerHeight()-24)/2);
        $loader.css('left',($loader.parent().innerWidth()-160)/2);
        $loader.ajaxStart(function(){
            $loader.css('display','block');
        });
        $loader.ajaxStop(function(){
            $loader.css('display','none');
            manageHeight();
        });
    }
</script>
<link href="<?php echo $this->getFavicon(); ?>" rel="shortcut icon" />