<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Newsletter subscription form
 *
 * @see Fox_Newsletter_View_Subscriber
 */
?>
<?php
if (($this->last) > 1) {
    $paramsArr = $this->getRequest()->getParams();
    $params = Fox::getAllParams($paramsArr);
    ?>
    <div class="pagination">
        <div class="pagination_controlls">
            <!-- First page link -->
            <?php if (isset($this->previous)): $params['page'] = $this->first; ?>
                <a class="enable_page first gradient" href="<?php echo $this->getUrl('*/*/*', $params); ?>"><?php echo $this->_('First') ?></a> 
            <?php else: ?>
                <span class="disabled first"><?php echo $this->_('First') ?></span> 
            <?php endif; ?>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): $params['page'] = $this->previous; ?>
                <a class="enable_page previous" href="<?php echo $this->getUrl('*/*/*', $params); ?>"> &nbsp;</a> 
            <?php else: ?>
                <span class="disabled previous"> &nbsp;</span> 
            <?php endif; ?>
            <!-- Numbered page links -->
            <span class="pagination-list">
                <?php foreach ($this->pagesInRange as $page): $params['page'] = $page; ?>
                    <?php if ($page != $this->current): ?>
                        <a class="enable_page" href="<?php echo $this->getUrl('*/*/*', $params); ?>"><?php echo $page; ?></a>
                    <?php else: ?>
                       <span class="current_page gradient"> <?php echo $page; ?></span>
                    <?php endif; ?>
                <?php endforeach; ?>
            </span>
            <!-- Next page link -->
            <?php if (isset($this->next)): $params['page'] = $this->next; ?>
                 <a class="enable_page next" href="<?php echo $this->getUrl('*/*/*', $params); ?>">&nbsp; </a> 
            <?php else: ?>
                 <span class="disabled next">&nbsp;</span> 
            <?php endif; ?>
            <!-- Last page link -->
            <?php if (isset($this->next)): $params['page'] = $this->last; ?>
                <a class="enable_page last gradient" href="<?php echo $this->getUrl('*/*/*', $params); ?>"><?php echo $this->_('Last') ?></a>
            <?php else: ?>
                <span class="disabled last"><?php echo $this->_('Last') ?></span>
            <?php endif; ?>
            <span class="page_counter"><?php echo $this->_('Page ')?><?php echo $this->current; ?><?php echo $this->_(' of ') ?><?php echo $this->last; ?></span>
        </div>
    </div>
    <?php
}?>