<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Administrator account setup
 *
 * @see Fox_Installer_View_Administrator
 */
?>
<div class="steps_left_cont local_main">
    <h2>Create Admin Account</h2>
    <form name="administrator_detail" id="administrator_detail" action="<?php echo $this->getAdministratorSetupUrl() ?>" method="post">
        <div class="local_in database_con per_info">
            <h3>Personal Information</h3>
            <ul>
                <li><div class="input-box">
                        <label for="firstname">First Name<span class="req">*</span></label>
                        <input type="text" class="required" name="firstname" id="firstname" value="<?php echo $this->getFirstName() ?>" />
                    </div>
                    <div class="input-box">
                        <label for="lastname">Last Name<span class="req">*</span></label>
                        <input type="text" class="required" name="lastname" id="lastname" value="<?php echo $this->getLastName() ?>" /></div>
                </li>
                <li><div class="input-box">
                        <label for="email">Email<span class="req">*</span></label>
                        <input type="text" class="required email" name="email" id="email" value="<?php echo $this->getEmail() ?>" />
                    </div>
                    <div class="input-box">
                        <label for="contact">Contact No.</label>
                        <input type="text" name="contact" id="contact" value="<?php echo $this->getContact() ?>" />
                    </div>
                </li>              
            </ul>
        </div>
        <div class="local_in log_info">
            <h3>Login Information</h3>
            <ul>
                <li class="user_name"><div class="input-box">
                        <label for="username">Username<span class="req">*</span></label>
                        <input type="text" name="username" class="required" id="username" value="<?php echo $this->getUsername() ?>" />
                    </div>
                </li>
                <li><div class="input-box">
                        <label for="password">Password<span class="req">*</span></label>
                        <input type="password" name="password" class="required" id="password" value="" />
                    </div>
                    <div class="input-box">
                        <label for="confirm_password">Confirm Password<span class="req">*</span></label>
                        <input type="password" class="required" name="confirm_password" id="confirm_password" value="" />
                    </div>
                </li>                
            </ul>
        </div>
        <div class="btn_div">
            <span class="req">*Required Fields</span>
            <button class="button" type="submit" name="Submit" value="Submit" id="submit"><span><span>Submit</span></span></button>
        </div>
    </form>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        foxForm=jQuery('#administrator_detail').foxForm({});
    });
</script>