<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * License agreement
 *
 * @see Fox_Installer_View_Installer
 */
?>
<div class="steps_left_cont">
    <h2>Welcome to Zendfox's Installation Wizard!</h2>
    <div class="inst_text_area">
        <p><strong><?php echo $this->getLicenseHtml(); ?></strong></p>
    </div>
    <div class="btn_div liscen">
          <form id="lisence" name="lisence" action="<?php echo $this->getLisenceUrl() ?>" method="post">
              <label><input type="checkbox" id="checkbox_lisence" name="checkbox_lisence" class="checkbox_lisence" /><span>I agree to the above terms and conditions.</span></label>
    <button class="disable" type="submit" disabled="disabled" name="Submit" value="Submit" id="submit"><span><span>Continue</span></span></button>
</form>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
    jQuery('#checkbox_lisence').click(function(){
        jQuery('#submit').removeClass();
        if(jQuery('#checkbox_lisence').attr('checked')){
            jQuery('#submit').attr('disabled', false);
            jQuery('#submit').addClass('enable');
        }else{
            jQuery('#submit').addClass('disable');
            jQuery('#submit').attr('disabled', true);
        }
    });
    });
</script>