<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
* @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Locale setup
 *
 * @see Fox_Installer_View_Installer
 */
?>
<div class="steps_left_cont local_main">
    <h2>Localization</h2>
    <form id="localization" name="localization" action="<?php echo $this->getLocalizationUrl() ?>" method="post">
    <div class="local_in sett">
<h3>Locale settings</h3>
<ul>
   <li><div class="input-box">
           <label>Locale <span class="req">*</span></label>
            <?php echo $this->getLocaleHtml() ?> </div></li>
    <li><div class="input-box">
                    <label>Time Zone<span class="req">*</span></label>
                    <?php echo $this->getTimezoneHtml() ?></div></li>
</ul>
</div>
    <div class="btn_div">
        <span class="req">*Required Fields</span>
        <button class="button" type="submit" name="Submit" value="Submit" id="submit"><span><span>Submit</span></span></button>
    </div>
</form>
</div>