<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Member change password page redirected from forgot password email
 *
 * @see Fox_Core_View_Template
 */
?>
<h3><?php echo $this->_('Change');?> <span><?php echo $this->_('Password');?></span></h3>
<div class="wrapper_change_pass">
    <form name="change-password" id="change-password" method="post" action="" >
        <table width="100%" class="change_pass_table">            
            <tr class="row">
                <td width="36%" class="label"><label><strong><?php echo $this->_('New Password');?></strong></label>  </td>
                <td width="64%" class="ele"><input type="password" name="password" id="password" class="required"/>
                    <input type="hidden" name="member_id" id="member_id" />
                </td>
            </tr>
            <tr class="row">
                <td class="label"><label><strong><?php echo $this->_('Confirm New Password');?></strong></label>  </td>
                <td class="ele"><input type="password" name="c_password" id="c_password"  class="required"/></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <span class="change_but"><button type="submit" class="sub_change_but"><?php echo $this->_('Submit') ?></button></span>
                    <span class="back-login"> << &nbsp;<a href="<?php echo Fox::getHelper('member/data')->getLoginUrl() ?>" ><?php echo $this->_('Back to login');?> </a></span></td></tr>
        </table>
    </form>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        foxForm=jQuery('#change-password').foxForm({});
    });
</script>