<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Member change password page
 *
 * @see Fox_Member_View_Account_Profile
 */
?>


<div class="ChangeWrap">
<h3><?php echo $this->_('Change Password');?></h3>
<div class="wrapper_change_pass">
    <form name="change-password" id="change-password" method="post" action="<?php echo $this->getChangePasswordUrl() ?>" >
        <table width="100%" class="change_pass_table">
             <tr class="row_contact">
                        <td class="lebal_con" width="37%" height="35"><?php echo $this->_('Current Password');?> <span class="asterisk"> *</span></td>
                        <td width="5%">:</td>
                        <td width="58%"><input type="password" name="current_password" id="current_password" class="required"/></td>
                    </tr>
           
            <tr class="row_contact">
                <td class="lebal_con" height="35"><label><?php echo $this->_('New Password');?></label> <span class="asterisk"> *</span></td>
                 <td>:</td>
                <td class="ele"><input type="password" name="password" id="password" class="required"/></td>
            </tr>
            <tr class="row_contact" height="35">
                <td class="lebal_con"><label><?php echo $this->_('Confirm New Password');?></label> <span class="asterisk"> *</span></td>
                  <td>:</td>
                <td class="ele"><input type="password" name="c_password" id="c_password" class="required"/></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>

                <td>
                    <span class="change_but"><button type="submit" class="sub_but submit_button"><?php echo $this->_('Submit') ?></button></span></td></tr>
        </table>
    </form>
</div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        foxForm=jQuery('#change-password').foxForm({});
    });
</script>