<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Member edit profile image page
 *
 * @see Fox_Member_View_Account_Profile
 */
?>
<div class="editImage">
<h3><?php echo $this->_('Edit Image');?></h3>
<div class="wrapper_cange_pass">
    <form name="change-image" id="change-image" method="post" action="<?php echo $this->getEditImageUrl() ?>" enctype="multipart/form-data" >
        <table width="100%" class="change_pass_table">
            <tr class="row">
                <td class="label"><?php echo $this->_('Edit Image');?></td>
                <td class="ele"><input type="file" name="member_image" id="member_image" class="required image"/></td>
                <td class="remove">
                    <?php if($this->isImageExists()): ?>
                        <a href="<?php echo $this->getRemoveImageUrl() ?>" title="Remove Image"><?php echo $this->_('Remove Image');?></a>
                    <?php endif; ?>
                </td>
            </tr>
           <tr>
                <td>&nbsp;</td>
                <td>
                    <span class="change_but"><button type="submit" class="sub_but"><?php echo $this->_('Submit') ?></button></span></td></tr>
        </table>
    </form>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        foxForm=jQuery('#change-image').foxForm({});
    });
</script>
