<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */
/**
 * Member edit profile page
 *
 * @see Fox_Member_View_Account_Profile
 */
?>
<div class="registration">
    <h3><?php echo $this->_('Edit Profile');?></h3>
    <div class="tab_container"><?php echo $this->getContent('edit_profile_form') ?></div>
</div>
<script type="text/javascript" src="<?php echo $this->themeUrl('js/formTabContainer.js') ?>"></script>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.tab_container').foxFormTabContainer({formObj:foxForm});
    });
</script>
