<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Member forgot password page
 *
 * @see Fox_Core_View_Template
 */
?>
<div class="forgetWrap">
    <div class="title_bar">
<h2><?php echo $this->_('Forgot Your');?> <span><?php echo $this->_('Password');?></span></h2>
</div>
<div class="login_page_right">
    <div class="login_member_index">
            <div class="all_login_wrap_index">
                    <h4><?php echo $this->_('Lost your Password ? Enter your email id here
and we will send you an email having change password link.');?></h4>
                <form name="member-forget-password" id="member-forget-password" method="post" action="" >                    
                    <div class="member_box_login_index">
                    <span class="lebal_login_sp_index"><?php echo $this->_('Email Id');?>*</span> <span class="text_box_mm"><input type="text" name="email_id" class="input_bor_index required email" /></span></div>
                    <div class="log_but_wrap_index"><span class="log_but_sp_index"><button type="submit" class="login_but_index submit_button"><?php echo $this->_('Submit') ?></button></span>
                    <span class="back-login"> << &nbsp;<a href="<?php echo Fox::getHelper('member/data')->getLoginUrl() ?>" ><?php echo $this->_('Back to login');?> </a></span>
                    </div>
                </form>
            </div>            
        </div>
    </div>
</div></div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        foxForm=jQuery('#member-forget-password').foxForm({});
    });
</script>