<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 */
/**
 * Admin dashboard page
 *
 * @see Fox_Admin_View_Dashboard
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */
?>


<script src="<?php echo $this->themeUrl('js/analytics/swfobject_modified.js') ?>" type="text/javascript"></script>

<div class="admin_page_title">
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <h1>Dashboard</h1>
            </td>
        </tr>
    </table>
</div>
<div class="tab_container dashboard_main">
    <div class="dashboard_left">
        <ul>
            <li>
                <?php echo $this->getContent('recent_members'); ?>
            </li>
            <li>
                <?php echo $this->getContent('recent_contacts'); ?>
            </li>
        </ul>
    </div>

    <div class="dashboard_right">
        <div class="dashboard_right_cont">
            <?php if($this->isChartEnabled()): ?>
            <?php $this->saveAnalyticsData(); ?>
          <object id="FlashID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="650" height="512">
              <param name="movie" value="<?php echo $this->themeUrl('flash/dashboard.swf') ?>" />
              <param name="quality" value="high" />
              <param name="wmode" value="opaque" />
              <param name="swfversion" value="6.0.65.0" />
              <param name="FlashVars" value="baseUrl=<?php echo Fox::getUrl('admin/analytics/index'); ?>" />
              <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -->
              <param name="expressinstall" value="<?php echo $this->themeUrl('js/analytics/expressInstall.swf') ?>" />
              <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -->
              <!--[if !IE]>-->
              <object type="application/x-shockwave-flash" data="<?php echo $this->themeUrl('flash/dashboard.swf') ?>" width="650" height="512" FlashVars="baseUrl=<?php echo Fox::getUrl('admin/analytics/index'); ?>">
                <!--<![endif]-->
                <param name="quality" value="high" />
                <param name="wmode" value="opaque" />
                <param name="swfversion" value="6.0.65.0" />
                <param name="FlashVars" value="baseUrl=<?php echo Fox::getUrl('admin/analytics/index'); ?>" />
                <param name="expressinstall" value="Scripts/expressInstall.swf" />
                <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -->
                <div>
                  <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>
                  <p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" width="112" height="33" /></a></p>
                </div>
                <!--[if !IE]>-->
              </object>
              <!--<![endif]-->
          </object>
            <?php else: ?>
            <div class="disabled_chart_report">Your chart is disabled. To enable chart <a href="<?php echo $this->getAnalyticsSettingUrl(); ?>">Click Here</a></div>
            <?php endif; ?>
        </div>
    </div>
</div>
