<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */
/**
 * Contact request page
 *
 * @see Fox_Core_View_Template
 */
?>
<div class="cont_page_wrap">
    <div class="cont_page">
        <div class="title_bar">
            <h2><?php echo $this->_('Contact '); ?><span><?php echo $this->_('Us'); ?></span></h2>
        </div>
        <div class="contact_form">
            <form name="contact" id="contact" method="post" action="" >
                <table style="width: 100%;" border="0" cellspacing="0" cellpadding="0">
                    <tbody>
                        <tr class="row_contact">
                            <td width="352%" colspan="4" class="lebal_con">
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                        <td width="22%" class="lebal_con"><?php echo $this->_('Name'); ?><span class="asterisk">*</span></td>
                                        <td width="2%">&nbsp;</td>
                                        <td width="76%" class="lebal_con"><?php echo $this->_('Email'); ?><span class="asterisk">*</span></td>
                                    </tr>
                                    <tr>
                                        <td height="30"><input class="text_contact required" type="text" name="name" id="name" /></td>
                                        <td>&nbsp;</td>
                                        <td><input class="text_contact required email" type="text" name="email" id="email" /></td>
                                    </tr>
                                </table>
                            </td>
                            <td width="48%"></td>
                        </tr>
                        <tr class="row_contact">
                            <td colspan="4" class="lebal_con"><?php echo $this->_('Subject'); ?><span class="asterisk">*</span></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr class="row_contact">
                            <td colspan="4" height="30"><input class="text_contact_subject required" type="text" name="subject" id="subject" /></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr class="row_contact">
                            <td colspan="4" class="lebal_con"><?php echo $this->_('Message'); ?><span class="asterisk">*</span></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr class="row_contact">
                            <td colspan="4"><textarea name="message" id="message" class="required"></textarea></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr class="row_contact">
                            <td colspan="4">&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr class="row_contact">
                            <td colspan="4"><input class="submit_button" type="submit" value="Submit" /></td>
                            <td>&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        foxForm = jQuery('#contact').foxForm({});
    });
</script>