<?php
/**
 * Zendfox Framework
 *
 * LICENSE
 *
 * This file is part of Zendfox.
 *
 * Zendfox is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zendfox is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zendfox in the file LICENSE.txt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    views
 * @package     core_default
 * @author      Zendfox Team of Unicode Systems <zendfox@unicodesystems.in>
 * @copyright   Copyright (c) 2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license     http://www.gnu.org/licenses/  GNU General Public License
 */

/**
 * Header content
 *
 * @see Fox_Core_View_Html_Header
 */
?>
<div class="header-top">
    <div class="header-top-logo"><a href="<?php echo Fox::getUrl('') ?>"><img src="<?php echo $this->themeUrl('images/logo.png'); ?>"  alt="unicode logo"/></a></div>
    </div>
<?php echo $this->getContent('top-banner'); ?>
<div class="root_bar">
    <h2>Zendfox <span>Installer</span></h2>
</div>
<script type="text/javascript" >
    jQuery(document).ready(function(){
        jQuery("#loginid").click(function(){
            jQuery(this).next('div.popup_login').slideToggle('fast');
        });
    });
</script>